### ISSUE TITLE
Dashboard doesn't work in Internet Explorer 11

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#119]
The client is trying to load something from a CDN and doesn't work correctly. Should be able to load in an isolated environment.

**Comment by adamdriscoll** [comment]
> TypeError: Object doesn't support property or method 'startsWith'
>    {
>       [functions]: ,
>       __proto__: { },
>       description: "Object doesn't support property or method 'startsWith'",
>       message: "Object doesn't support property or method 'startsWith'",
>       name: "TypeError",
>       number: -2146827850,
>       stack: "TypeError: Object doesn't support property or method 'startsWith'
>    at o (http://localhost:8081/bundle.js:11:11302)
>    at value (http://localhost:8081/bundle.js:48:263027)
>    at c (http://localhost:8081/bundle.js:48:288835)
>    at beginWork (http://localhost:8081/bundle.js:48:290244)
>    at a (http://localhost:8081/bundle.js:48:302629)
>    at c (http://localhost:8081/bundle.js:48:303129)
>    at u (http://localhost:8081/bundle.js:48:303626)
>    at h (http://localhost:8081/bundle.js:48:305648)
>    at m (http://localhost:8081/bundle.js:48:305150)
>    at i.enqueueSetState (http://localhost:8081/bundle.js:48:286427)"
>    }
>
