### ISSUE TITLE
Latest update doesn't install properly

### ISSUE THREAD

**Issue by v-tbert** [adamdriscoll/poshprotools#17]
These seem to be the relevant bits from the install log:

8/23/2017 8:08:31 AM - -------------------------------------------
8/23/2017 8:08:31 AM - Microsoft VSIX Installer
8/23/2017 8:08:31 AM - -------------------------------------------
8/23/2017 8:08:31 AM - Initializing Install...
8/23/2017 8:08:31 AM - Extension Details...
8/23/2017 8:08:31 AM - 	Identifier         : PowerShellToolsPro.AdamRDriscoll.6eeb32f4-0469-4cbd-836d-eca7cb725a06
8/23/2017 8:08:31 AM - 	Name               : PowerShell Pro Tools for Visual Studio 2017
8/23/2017 8:08:31 AM - 	Author             : Adam Driscoll
8/23/2017 8:08:31 AM - 	Version            : 1.0.187
8/23/2017 8:08:31 AM - 	Description        : Professional enhancements to the PowerShell editing experience in Visual Studio.
8/23/2017 8:08:31 AM - 	Locale             : en-US
8/23/2017 8:08:31 AM - 	MoreInfoURL        : https://www.poshtools.com/
8/23/2017 8:08:31 AM - 	InstalledByMSI     : False
8/23/2017 8:08:31 AM - 	SupportedFrameworkVersionRange : [4.5,)
8/23/2017 8:08:31 AM - 
8/23/2017 8:08:31 AM - 	SignatureState     : Unsigned
8/23/2017 8:08:31 AM - 	Supported Products : 
8/23/2017 8:08:31 AM - 		Microsoft.VisualStudio.Community
8/23/2017 8:08:31 AM - 			Version : [15.0]
8/23/2017 8:08:31 AM - 
8/23/2017 8:08:31 AM - 	References         : 
8/23/2017 8:08:31 AM - 	Prerequisites      : 
8/23/2017 8:08:31 AM - 		-------------------------------------------------------
8/23/2017 8:08:31 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
8/23/2017 8:08:31 AM - 		Name         : Visual Studio core editor
8/23/2017 8:08:31 AM - 		Version      : [15.0,16.0)
8/23/2017 8:08:31 AM - 

8/23/2017 8:09:00 AM - Windows Installer found the package 'Microsoft.Azure.PowerShell,version=15.0.26621.2' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
8/23/2017 8:09:00 AM - Package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.15063.0' is not in the supported version range '(,6.2)'.
8/23/2017 8:10:06 AM - Unable to find component in product catalog with this ID: Component.PowerShellToolsPro.AdamRDriscoll.6eeb32f4-0469-4cbd-836d-eca7cb725a06,version=1.0.184
8/23/2017 8:10:06 AM - Install Error : System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by adamdriscoll** [comment]
@v-tbert I will take a look. Thanks for reporting this.

**Comment by adamdriscoll** [comment]
@v-tbert Can you try to uninstall the previous version and install the new version? It's reporting the 184 build is missing while the new build is 187,

**Comment by v-tbert** [comment]
Apparently I cannot uninstall either. Is there a way to manually remove it?

From the uninstall log it looks like a similar error:

8/23/2017 2:40:02 PM - Uninstalling 'PowerShell Pro Tools for Visual Studio 2017', version 1.0.184.
8/23/2017 2:40:07 PM - Unable to find component in product catalog with this ID: Component.PowerShellToolsPro.AdamRDriscoll.6eeb32f4-0469-4cbd-836d-eca7cb725a06,version=1.0.184
8/23/2017 2:40:07 PM - System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)

**Comment by adamdriscoll** [comment]
You can try to rename the folder with the extension installed. If you search for PowerShellToolsPro in the Visual Studio installation directory, it should find the extension folder. Rename that folder and try to uninstall. If that works, install the new version. 

I've reached out to the extendVs Gitter group to see if they have any other recommendations.

**Comment by v-tbert** [comment]
Doing a directory search I found the extension installed at two locations. I deleted these folders and I was able to reinstall successfully:

c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\lrizlia2.5ed
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\plu2ozqq.xq5

**Comment by adamdriscoll** [comment]
Glad it's working. Feel free to re-open this if it happens again.
